DjangoDiary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('diary/', include('diary.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path("", views.index, name="index"),
    path("page/create/", views.page_create, name="page_create"),
    path("pages/", views.page_list, name="page_list"),
    path("pages/<uuid:page_id>/", views.page_detail, name="page_detail"),
    path("pages/<uuid:page_id>/update/", views.page_update, name="page_update"),
    path("pages/<uuid:page_id>/delete/", views.page_delete, name="page_delete")
]

accounts/models.py
from django.db import models

# Create your models here.

diary/models.py
import uuid
from pathlib import Path

from django.db import models


class Page(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
    title = models.CharField(max_length=100, verbose_name="タイトル")
    body = models.TextField(max_length=2000, verbose_name="本文")
    page_date = models.DateField(verbose_name="日付")
    # upload_toはどのフォルダにアップロードするか。settings.pyで設定したmediaのサブフォルダ
    picture = models.ImageField(upload_to='diary/picture/', blank=True, null=True, verbose_name='写真')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        picture = self.picture
        super().delete(*args, **kwargs)
        if picture:
            Path(picture.path).unlink(missing_ok=True)

diary/forms.py
from django.forms.models import ModelForm

from diary.models import Page


class PageForm(ModelForm):
    class Meta:
        model = Page
        fields = ['title', 'body', 'page_date', 'picture']

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
from datetime import datetime
from zoneinfo import ZoneInfo

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from diary.forms import PageForm
from diary.models import Page


class IndexView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        datetime_now = datetime.now(ZoneInfo('Asia/Tokyo')).strftime('%Y年%m月%d日 %H:%M:%S')
        return render(request, 'diary/index.html', {'datetime_now': datetime_now})


class PageCreateView(LoginRequiredMixin, View):
    # 入力画面を表示するときの関数
    @staticmethod
    def get(request):
        form = PageForm()
        return render(request, 'diary/page_form.html', {'form': form})

    # 入力画面から送信されたデータを処理するときの関数
    @staticmethod
    def post(request):
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # indexは urls.py に紐づいている
            return redirect('diary:index')
        else:
            return render(request, 'diary/page_form.html', {'form': form})


class PageListView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        # DBから全件を取得する
        page_all = Page.objects.order_by('-page_date')
        return render(request, 'diary/page_list.html', {'page_list': page_all})


class PageDetailView(LoginRequiredMixin, View):
    @staticmethod
    def get(request, page_id):
        # DBから指定されたIDのデータを取得する。取得できなかった場合は404
        page = get_object_or_404(Page, id=page_id)
        return render(request, 'diary/page_detail.html', {'page': page})


class PageUpdateView(LoginRequiredMixin, View):
    @staticmethod
    def get(request, page_id):
        page = get_object_or_404(Page, id=page_id)
        # 登録されていたデータを初期値として設定する
        form = PageForm(instance=page)
        return render(request, 'diary/page_update.html', {'form': form})

    @staticmethod
    def post(request, page_id):
        page = get_object_or_404(Page, id=page_id)
        form = PageForm(request.POST, request.FILES, instance=page)
        if form.is_valid():
            form.save()
            return redirect('diary:page_detail', page_id=page_id)
        else:
            return render(request, 'diary/page_update.html', {'form': form})


class PageDeleteView(LoginRequiredMixin, View):
    @staticmethod
    def get(request, page_id):
        page = get_object_or_404(Page, id=page_id)
        return render(request, 'diary/page_confirm_delete.html', {'page': page})

    @staticmethod
    def post(request, page_id):
        page = get_object_or_404(Page, id=page_id)
        page.delete()
        return redirect('diary:page_list')


index = IndexView.as_view()
page_create = PageCreateView.as_view()
page_list = PageListView.as_view()
page_detail = PageDetailView.as_view()
page_update = PageUpdateView.as_view()
page_delete = PageDeleteView.as_view()

templates/base/diary_base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>サプーの日記</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'diary/css/base.css' %}">
    <script src="{% static 'diary/js/base.js' %}"></script>
</head>
<body>
<h1><a href="{% url 'diary:index' %}">サプーの日記</a></h1>
{% block body %}
{% endblock %}
</body>
</html>

templates/diary/index.html
{% extends "base/diary_base.html" %}
{% block body %}

    <p>{{ datetime_now }}</p>
    <br>
    <a href="{% url 'diary:page_create' %}">日記を書く</a>
    <br>
    <a href="{% url 'diary:page_list' %}">ページ一覧</a>
    <br>
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">ログアウト</button>
    </form>

{% endblock %}

templates/diary/page_confirm_delete.html
{% extends "base/diary_base.html" %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        <p>このページを削除していいですか。</p>
        <button type="submit">削除</button>
    </form>
    <h2>{{ page.title }}</h2>
    <div>{{ page.page_date }}</div>
    <div>{{ page.body | linebreaksbr }}</div>
    {% if page.picture %}
        <img src="{{ page.picture.url }}" alt="">
    {% endif %}
{% endblock %}

templates/diary/page_detail.html
{% extends "base/diary_base.html" %}
{% block body %}
    <h2>{{ page.title }}</h2>
    <div>{{ page.page_date }}</div>
    <div>{{ page.body | linebreaksbr }}</div>
    {% if page.picture %}
        <img src="{{ page.picture.url }}" alt="">
    {% endif %}
    <br>
    <a href="{% url 'diary:page_update' page.id %}">編集</a>
    <a href="{% url 'diary:page_delete' page.id %}">削除</a>
{% endblock %}

templates/diary/page_form.html
{% extends "base/diary_base.html" %}
{% block body %}
    <h2>日記を書く</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">保存</button>
    </form>
{% endblock %}

templates/diary/page_list.html
{% extends "base/diary_base.html" %}
{% block body %}
    <ul>
        {% for page in page_list %}
            <li>{{ page.page_date }}: <a href="{% url 'diary:page_detail' page.id %}">{{ page.title }}</a></li>
        {% empty %}
            <div>日記のページが1つもありません。</div>
        {% endfor %}
    </ul>
{% endblock %}

templates/diary/page_update.html
{% extends "base/diary_base.html" %}
{% block body %}
    <h2>日記を書く</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">更新</button>
    </form>
{% endblock %}